const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
const UPDATE_FILTERED_MOVIES = 'UPDATE_FILTERED_MOVIES';
const UPDATE_MOVIES_BY_SPECIFIC_GENRE = 'UPDATE_MOVIES_BY_SPECIFIC_GENRE';

export {
    GET_ALL_MOVIES,
    GET_MOVIE_DETAILS,
    UPDATE_FILTERED_MOVIES,
    UPDATE_MOVIES_BY_SPECIFIC_GENRE
}